package miaoshaproject.dao;

import miaoshaproject.dataobject.ItemStockDAO;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int insert(ItemStockDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int insertSelective(ItemStockDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    ItemStockDAO selectByPrimaryKey(Integer id);

    ItemStockDAO selectByItemId(Integer ItemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int updateByPrimaryKey(ItemStockDAO record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}