package miaoshaproject.dao;

import miaoshaproject.dataobject.ItemDAO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int insert(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int insertSelective(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    ItemDAO selectByPrimaryKey(Integer id);

    List<ItemDAO> listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Mar 15 14:08:11 CST 2019
     */
    int updateByPrimaryKey(ItemDAO record);

    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}