package miaoshaproject.dao;

import miaoshaproject.dataobject.OrderDAO;

public interface OrderDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Mar 15 23:23:15 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Mar 15 23:23:15 CST 2019
     */
    int insert(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Mar 15 23:23:15 CST 2019
     */
    int insertSelective(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Mar 15 23:23:15 CST 2019
     */
    OrderDAO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Mar 15 23:23:15 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Mar 15 23:23:15 CST 2019
     */
    int updateByPrimaryKey(OrderDAO record);
}