package miaoshaproject.dao;

import miaoshaproject.dataobject.PromoDAO;

public interface PromoDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sat Mar 16 13:05:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sat Mar 16 13:05:59 CST 2019
     */
    int insert(PromoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sat Mar 16 13:05:59 CST 2019
     */
    int insertSelective(PromoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sat Mar 16 13:05:59 CST 2019
     */
    PromoDAO selectByPrimaryKey(Integer id);

    PromoDAO selectByItemId(Integer itemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sat Mar 16 13:05:59 CST 2019
     */
    int updateByPrimaryKeySelective(PromoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sat Mar 16 13:05:59 CST 2019
     */
    int updateByPrimaryKey(PromoDAO record);
}