package miaoshaproject.dao;

import miaoshaproject.dataobject.UserDAO;

public interface UserDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Mar 14 00:10:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Mar 14 00:10:11 CST 2019
     */
    int insert(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Mar 14 00:10:11 CST 2019
     */
    int insertSelective(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Mar 14 00:10:11 CST 2019
     */
    UserDAO selectByPrimaryKey(Integer id);

    UserDAO selectByTelephone(String telephone);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Mar 14 00:10:11 CST 2019
     */
    int updateByPrimaryKeySelective(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Mar 14 00:10:11 CST 2019
     */
    int updateByPrimaryKey(UserDAO record);
}